package config

const (
	ROLE                            = "role"
	PERMISSIONS                     = "permissions"
	ACCRESS_TOKEN                   = "accesstoken"
	REFRESH_TOKEN                   = "refreshtoken"
	TOKEN                           = "token"
	OK                              = "OK"
	USER_TYPE_EMPLOYER              = "EMPLOYER"
	USER_TYPE_JOBSEEKER             = "JOBSEEKER"
	USER_TYPE_ANONYMOUS             = "ANONYMOUS"
	USER_TYPE_SYSTEM                = "SYSTEM"
	PROFILE_PHOTO                   = "PROFILE_PHOTO"
	RESUME                          = "RESUME"
	COMPANY_LOGO                    = "COMPANY_LOGO"
	COMPANY_COVER                   = "COMPANY_COVER"
	JOBSEEKER_PROFILE               = "JOBSEEKER_PROFILE"
	Employer_Profile                = "Employer_Profile"
	OTP                             = "otp"
	EMAIL                           = "email"
	PHONE_NUMBER                    = "phoneNumber"
	USERNAME                        = "username"
	DEVICE_TOKEN                    = "deviceToken"
	DEVICE_TYPE                     = "deviceType"
	FIREBASE_SIGNIN_PROVIDER_APPLE  = "apple.com"
	FIREBASE_SIGNIN_PROVIDER_GOOGLE = "google.com"
	CP_PERMISSION                   = "CP"
	DEFAULT_USER_PERMISSION         = "DEFAULT_USER"
	PENDING                         = "pending"
)
