package config

const (
	ROLE                = "role"
	PERMISSIONS         = "permissions"
	ACCRESS_TOKEN       = "accesstoken"
	REFRESH_TOKEN       = "refreshtoken"
	TOKEN               = "token"
	OK                  = "OK"
	GOOGLE              = "GOOGLE"
	FACEBOOK            = "FACEBOOK"
	APPLE               = "APPLE"
	SYSTEM_ACC          = "SYSTEM_ACC"
	ANONYMOUS           = "Anonymous"
	ANDROID             = "ANDROID"
	IOS                 = "IOS"
	SmsOtp              = "SmsOtp"
	SendOtp             = "SendOtp"
	Phone               = "phone"
	SUCCESS             = "SUCCESS"
	ERROR               = "ERROR"
	UPDATE_USER_ACTION  = "Cập nhật người dùng"
	UPDATE_USER         = "UPDATE_USER"
	LOCK_USER           = "LOCK_USER"
	LOCK_USER_ACTION    = "Khóa người dùng"
	SmsInit             = "init"
	SmsVerify           = "verify"
	USER_TYPE_CMS       = "CMS"
	USER_TYPE_MOBILE    = "MOBILE"
	USER_TYPE_ANONYMOUS = "ANONYMOUS"

	PROVIDER_PHONE = "PHONE"

	FIREBASE_SIGNIN_PROVIDER_APPLE  = "apple.com"
	FIREBASE_SIGNIN_PROVIDER_GOOGLE = "google.com"
	CP_PERMISSION                   = "CP"
	DEFAULT_USER_PERMISSION         = "DEFAULT_USER"
	DELETE_DEVICE                   = "DELETE_DEVICE"
	LOGIN                           = "LOGIN"
	CHANGE_PASSWORD                 = "CHANGE_PASSWORD"
	REGISTER                        = "REGISTER"
	FORGOT_PASSWORD                 = "FORGOT_PASSWORD"
	COUNTER                         = "COUNTER"
	COUNTER_ERROR                   = "COUNTER_ERROR"
	MAX_NUMER_OTP_SENDED_IN_DAY     = 15
	MAX_NUMER_OTP_ERROR_BY_TRACE_ID = 3
)
