package config

const (
	ROLE               = "role"
	PERMISSIONS        = "permissions"
	ACCRESS_TOKEN      = "accesstoken"
	REFRESH_TOKEN      = "refreshtoken"
	TOKEN              = "token"
	OK                 = "OK"
	VMG_GMAIL          = "@vmgmedia.vn"
	GOOGLE             = "GOOGLE"
	FACEBOOK           = "FACEBOOK"
	APPLE              = "APPLE"
	SYSTEM_ACC         = "SYSTEM_ACC"
	ANONYMOUS          = "Anonymous"
	ANDROID            = "ANDROID"
	IOS                = "IOS"
	SmsOtp             = "SmsOtp"
	SendOtp            = "SendOtp"
	Phone              = "phone"
	SUCCESS            = "SUCCESS"
	ERROR              = "ERROR"
	UPDATE_USER_ACTION = "Cập nhật người dùng"
	UPDATE_USER        = "UPDATE_USER"
	LOCK_USER          = "LOCK_USER"
	LOCK_USER_ACTION   = "Khóa người dùng"
	SmsInit            = "init"
	SmsVerify          = "verify"
)
